# Generated by Django 3.1.3 on 2020-11-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earthquake',
            name='origin_time',
            field=models.DateTimeField(),
        ),
    ]
